Clear private polynomial after DKG
stacks-network/wsts pull request #7
Opened 2024-03-22 18:32 UTC by xoloki

## Description
This PR clears the private polynomial after DKG is complete.  Doing so provides a security benefit, since there is no need to store this information, and leaking it allows various attack scenarios.  We did not clear this data previously because we weren't persisting anything, so it was moot.  Now that version `9` has full persistence support this has become necessary.

## Type of Change
This is a security fix that will be necessary once applications like `stacks-signer` start persisting data.

## Does this introduce a breaking change?
This change adds a `threshold` field to `v1::Party`, and passes it as a parameter to the public `v1::Party::load` `fn`.  Applications however should not need to change, since they deal with the `traits::Signer` and state machine interfaces not the low level `Party` interfaces.

## Are documentation updates required?
No

## Testing information
`cargo test` tests still pass without any updates.

## Checklist
- [x] Code is commented where needed
- [] Unit test coverage for new or modified code paths

2024-03-22 19:48 UTC, netrome requested changes
Looks good for the most of it, but I'd like to avoid the panics if possible - or at least have them documented.

2024-03-22 19:48 UTC, netrome commented on src/v1.rs
> +            panic!("no polynomial");
I know it's a breaking API change, but I'd prefer to see this being updated to return an `Option<_>` or a `Result<_>` if you want to be explicit, now when the operation may fail.

At least, the panic should be documented in the doc string as per https://rust-lang.github.io/api-guidelines/documentation.html#function-docs-include-error-panic-and-safety-considerations-c-failure.

2024-03-22 19:48 UTC, netrome commented on src/v1.rs
> +            panic!("no polynomial");
Same here

2024-03-22 19:48 UTC, netrome commented on src/v2.rs
> +            panic!("no polynomial");
And here

2024-03-22 19:50 UTC, xoloki commented on src/v1.rs
> +            panic!("no polynomial");
Yeah I wasn't super happy with the `panic`, it just seemed cleaner to avoid API breakage.  But in general I hate `panic` in library code so I'm remove them and bite the API change bullet.

2024-03-22 19:50 UTC, xoloki commented on src/v1.rs
> +            panic!("no polynomial");
Yeah

2024-03-22 19:51 UTC, xoloki commented on src/v1.rs
> +            panic!("no polynomial");
Luckily we're already doing a major semver change so there's really no excuse not to just change the API.

2024-03-22 19:55 UTC, netrome commented on src/state_machine/coordinator/mod.rs
> +        }
This could be a nice but small utility method on the `Coordinator` trait.

2024-03-22 19:56 UTC, jcnelson commented on src/v1.rs
> +            panic!("no polynomial");
I for one will gladly endure API breakage if it means removing panicky code :+1:

2024-03-22 19:57 UTC, netrome reviewed
Also, shouldn't we add some logic to the `Coordinator` types so that they will clear their signers polynomials when they are done with a DKG round?

2024-03-22 19:59 UTC, jcnelson reviewed
Once the panics are removed I'll approve.  Otherwise LGTM.

How sensitive are these polynomials?  Should we explicitly clear them in RAM before they get dropped, or is just dropping them good enough?

2024-03-22 20:11 UTC, netrome commented
> Once the panics are removed I'll approve. Otherwise LGTM.
> 
> How sensitive are these polynomials? Should we explicitly clear them in RAM before they get dropped, or is just dropping them good enough?

@xoloki knows this better, so please correct me if I'm wrong, but I don't think these polynomials are that sensitive. A malicious actor would have to collect **all** of them in order to be able to forge a signature, and in this scenario they are better of just stealing the persisted party shares instead, since then they only need 70% to produce a valid signature.

There could of course be attack vectors I'm not foreseeing here, but clearing them in RAM seems overkill to me.

2024-03-22 20:23 UTC, xoloki commented
@netrome is correct; you need to steal all the polys (specifically their constant coefficients) in order to forge a signature.  It seems overkill to worry about them being in RAM.

At some point we do need to address encryption of data at rest in `stacks-signer`, once we get basic functionality in place via https://github.com/stacks-network/stacks-core/pull/4570.  But that's out of scope for this library.

2024-03-22 20:40 UTC, xoloki commented
> Also, shouldn't we add some logic to the `Coordinator` types so that they will clear their signers polynomials when they are done with a DKG round?

The `Coordinator` state machines don't contain `Signer` traits, only the `Signer` state machine does.  And the `Signer` state machine doesn't actually track when DKG is complete, only the `Coordinator` state machines do.

The logical place to do the clearing is at the application layer, e.g. `stacks-signer`.  It contains both `Coordinator` and `Signer` state machines, so it can know when it's safe to clear.  And as we progress with the `sBTC` and `DLC` projects, we will not necessarily want to clear the polys; keeping them around will allow re-running DKG and getting the same public key with different signature shares.

2024-03-22 20:44 UTC, xoloki commented on src/v1.rs
> +            panic!("no polynomial");
@netrome since these functions return `Vec` and `HashMap` respectively, we could avoid both `panic!` and API change: instead just `warn!` then return an empty container.  Do you think it's necessary to have an explicit `Option` or `Result`?

2024-03-22 20:44 UTC, netrome commented
> > Also, shouldn't we add some logic to the `Coordinator` types so that they will clear their signers polynomials when they are done with a DKG round?
> 
> The `Coordinator` state machines don't contain `Signer` traits, only the `Signer` state machine does. And the `Signer` state machine doesn't actually track when DKG is complete, only the `Coordinator` state machines do.
> 
> The logical place to do the clearing is at the application layer, e.g. `stacks-signer`. It contains both `Coordinator` and `Signer` state machines, so it can know when it's safe to clear. And as we progress with the `sBTC` and `DLC` projects, we will not necessarily want to clear the polys; keeping them around will allow re-running DKG and getting the same public key with different signature shares.

Right, makes sense :ok_hand: thanks for the explanation.

2024-03-22 20:49 UTC, netrome commented on src/v1.rs
> +            panic!("no polynomial");
Right, yeah returning an empty collection in that scenario makes sense as long as we document it. Nice catch,

2024-03-22 21:22 UTC, netrome approved these changes
LGTM, though I wasn't expecting to see Options in any return values after the previous discussion.

2024-03-22 21:22 UTC, netrome commented on src/v1.rs
> +            None
The `PolyCommitment` struct is essentially just wrapping a collection so we could let `poly` be an empty vec here and skip the `Option` in the return type. The `id` should be known in both cases.

I'm fine with either though.

2024-03-22 21:22 UTC, xoloki commented
Ok @netrome @jcnelson the `panic!`s are gone without breaking the external APIs.  I make minor changes to the internal `Party` APIs but no one outside of the library should be using those.

2024-03-22 21:23 UTC, xoloki commented on src/v1.rs
> +            panic!("no polynomial");
Fixed

2024-03-22 21:26 UTC, xoloki commented on src/v1.rs
> +            None
We can't actually make a `PolyCommitment` with an empty polynomial, since the commitment contains a schnorr proof of knowledge of the constant coefficient of the poly.  Returning `None` here is the cleanest thing to do.

2024-03-22 21:27 UTC, netrome commented
> Ok @netrome @jcnelson the `panic!`s are gone without breaking the external APIs. I made minor changes to the internal `Party` APIs but no one outside of the library should be using those.

Nice stuff, approved :heavy_check_mark:

2024-03-22 21:31 UTC, jferrant approved these changes

2024-03-22 21:44 UTC, netrome commented on src/v1.rs
> +            None
Ah right I see. Makes sense, thanks for explaining :pray:

2024-03-23 19:13 UTC, xoloki commented
Waiting on one of @jcnelson  or @kantai  before merging

2024-03-25 17:55 UTC, merged